Controllers/AppController.cs
using DutchTreat.Data;
using DutchTreat.Services;
using DutchTreat.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DutchTreat.Controllers
{
    public class AppController:Controller
    {
        private readonly IDutchRepository _dutchRepository;
        private readonly IMailService _mailService;

        public AppController(IDutchRepository dutchRepository, IMailService mailService)
        {
            _dutchRepository = dutchRepository;
            _mailService = mailService;
        }
        public IActionResult Index()
        {
            return View();
        }
        //Below will just use localhost/contact not 
        //localhost/app/contact
        [HttpGet("contact")]
        public IActionResult Contact()
        {
            return View();
        }
        [HttpPost("contact")]
        public IActionResult Contact(ContactViewModel model)
        {
            if (ModelState.IsValid)
            {
                _mailService.SendEmail("test@ak", model.Subject, model.Message);
                ViewBag.UserMessage = "Email was sent";
                ModelState.Clear();
            }
            else
            {
                //show errors;
            }
            return View();
        }
        public IActionResult About()
        {
            ViewBag.Title = "Contact Us";
            return View();
        }

        [Authorize]
        public IActionResult Shop()
        {
            var results = _dutchRepository.GetAllProducts().ToList();
            return View(results);
        }
        

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Dutch Treat: @ViewBag.Title</title>

    <link href="~/node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/node_modules/font-awesome/css/font-awesome.min.css" rel="stylesheet" />

    <link href="~/css/site.css" rel="stylesheet" />
</head>
<body>
    <header class="container">

        <nav class="navbar navbar-dark bg-dark navbar-expand-md">
            <h1 class="navbar-brand">
                <i class="fa fa-paint-brush">Welcome to Dutch Threat</i></h1>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#theMenu">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div id="theMenu" class="navbar-collapse collapse">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link" asp-controller="App" asp-action="Index">Home</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="App" asp-action="Contact">Contact</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="App" asp-action="About">About</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="App" asp-action="Shop">Shop</a></li>
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item"><a class="nav-link" asp-controller="Account" asp-action="Login">Login</a></li>
                    }
                    else
                    {
                        <li class="nav-item"><a class="nav-link" asp-controller="Account" asp-action="Logout">Logout</a></li>
                    }
                </ul>
            </div>
        </nav>
    </header>
    <section class="container">
        <h2 class="text-center">@ViewBag.Title</h2>
        @RenderBody()
    </section>
    <footer class="container">
        <div class="text-center">
            Copyright 2019 Dutch Threat LLC
        </div>
    </footer>


    <script src="~/node_modules/jquery/dist/jquery.min.js"></script>

    <script src="~/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/index.js"></script>
    @RenderSection("scripts", false)
</body>
</html>